FROM python:3.11-slim-buster

RUN apt-get update && \
    apt-get install -y sudo gcc

WORKDIR /usr/streamlit

COPY streamlit/requirements.txt .
RUN pip install -U pip && pip install -r requirements.txt
